config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'

  get '/residents', to: 'pages#residents', as: 'residents'

  resources :issues, except: [ :show ] do
    resources :comments, except: [ :show ]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :issue
  belongs_to :user

  validates :content, presence: true
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, :body, :start_date, presence: true
  validates_inclusion_of :is_resolved, in: [true, false]
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body

  validates :name, :email, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :apartment_number, presence: true

  def after_confirmation
    :send_welcome_email
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:apartment_number, :email, :password, :password_confirmation])
  end

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || residents_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    @issue = Issue.find(params[:issue_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @issue = Issue.find(params[:issue_id])
    @comment.issue = @issue
    if @comment.save
      redirect_to residents_path, notice: "Your comment has been added"
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to residents_path, notice: "Your comment has been updated"
    end
  end

  def delete
    @issue = Issue.find(params[:id])
    if @issue.destroy!
      redirect_to residents_path, notice: "Your comment has been deleted"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
    @issues = Issue.all
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.new(issue_params)
    @issue.user = current_user
    if @issue.save!
      redirect_to residents_path, notice: "Your issue has been added to the list"
    end
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def update
    @issue = Issue.find(params[:id])
    if @issue.update!(issue_params)
      redirect_to residents_path, notice: "Your issue has been updated"
    end
  end

  def delete
    @issue = Issue.find(params[:id])
    if @issue.destroy!
      redirect_to residents_path, notice: "Your issue has been deleted"
    end
  end

  private
  def issue_params
    params.require(:issue).permit(:title, :body, :start_date, :is_resolved, :end_date)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid? && verify_recaptcha(model: @message)
      MessageMailer.contact(@message).deliver_now
      redirect_to root_path, notice: "Message received, thanks!"
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def residents
    @issues = Issue.all
    @current_issues = @issues.where("is_resolved = ?", "false")
    @past_issues = @issues.where("is_resolved = ?", "true")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_edit_comment_modal.html.erb
<!-- Modal -->
<div class="modal fade" id=<%= "editCommentForIssue_#{issue.id}" %> tabindex="-1" role="dialog" aria-labelledby=<%= "editCommentForIssue_#{issue.id}Title" %> aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id=<%= "editCommentForIssue_#{issue.id}Title" %>>Edit Comment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'comments/form', issue: issue, comment: comment %>
      </div>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [issue, comment] do |f| %>
  <%= comment.errors.full_messages.join(', ') %>

  <div class="form-inputs">

    <%= f.input :content, label: false, placeholder: "comment on this issue here" %>
  </div>
  <br>
  <%= f.button :submit, 'Submit', class: "btn-block btn-outline-primary" %>
<% end %>

app/views/comments/_new_comment_modal.html.erb
<!-- Modal -->
<div class="modal fade" id=<%= "newCommentForIssue_#{issue.id}" %> tabindex="-1" role="dialog" aria-labelledby=<%= "newCommentForIssue_#{issue.id}Title" %> aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id=<%= "newCommentForIssue_#{issue.id}Title" %>>New Comment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'comments/form', issue: issue, comment: Comment.new %>
      </div>
    </div>
  </div>
</div>

app/views/comments/new.html.erb
<%= render 'form', issue: @issue, comment: @comment %>

app/views/issues/_edit_issue_modal.html.erb
<!-- Modal -->
<div class="modal fade" id=<%= "editIssue_#{issue.id}" %> tabindex="-1" role="dialog" aria-labelledby=<%= "editIssue_#{issue.id}Title" %> aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id=<%= "editIssue_#{issue.id}Title" %>>Edit Issue</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'issues/form', issue: issue %>
      </div>
    </div>
  </div>
</div>

app/views/issues/_form.html.erb
<%= simple_form_for issue do |f| %>
  <%= issue.errors.full_messages.join(', ') %>

  <div class="form-inputs">
    <%= f.input :title, label: 'Issue title', placeholder: 'e.g. "elevator broken", "slow maintenance", etc.', required: true %>
    <%= f.input :body, label: 'Describe your issue', placeholder: "Provide as much detail as you want", required: true %>
    <%= f.input :start_date, label: 'When did this issue first occur?', required: true %>
    <%= f.label "Has the issue been resolved?", required: true %>
    <%= f.input :is_resolved,
                :collection => [['Yes', true], ['No', false]],
                :label => false,
                :as => :radio_buttons,
                :item_wrapper_class => 'inline mx-3',
                :checked => false %>
    <div id="end-date" class="d-none">
      <%= f.label 'When was the issue resolved?' %>
      <%= f.input :end_date, label: false %>
    </div>
  </div>
  <br>
  <%= f.button :submit, 'Submit', class: "btn-block btn-outline-primary" %>
<% end %>

app/views/issues/_issue_list.html.erb
<div class="my-3">
  <div class="current-issue-title">
    <h2>Current Issues</h2>
    <%= render 'issues/new_issue_modal.html.erb' %>
  </div>
  <% @current_issues.each do |issue| %>
    <div class="container-fluid py-2 border-top border-bottom">
      <div class="row">
        <div class="col-xs-12 col-sm-6 clickable">
          <strong>
            <i class="fas fa-angle-right display-change"></i>
            <i class="fas fa-caret-down d-none display-change"></i>
            <%= issue.title.titleize %>
          </strong>
        </div>
        <div class="col-sm-3">
          <%= "posted by: Apartment #{issue.user.apartment_number}" %>
        </div>
        <div class="col-sm-3">
          <%= "occured on: #{issue.start_date}" %>
        </div>
      </div>
      <div class="d-none display-change pt-1">
        <p>
          <%= issue.body %>
        </p>
        <%= link_to "Add a comment", "#newCommentForIssue_#{issue.id}", class: "small-link", data: {toggle: "modal", target: "#newCommentForIssue_#{issue.id}"} %>
        <%= render 'comments/new_comment_modal', issue: issue %>
        -
        <% if current_user == issue.user %>
          <%= link_to "Edit issue", "#editIssue_#{issue.id}", class: "small-link", data: {toggle: "modal", target: "#editIssue_#{issue.id}"} %>
          <%= render 'issues/edit_issue_modal', issue: issue %>
          -
        <% end %>
        <%= link_to "Mark issue as resolved", issue_path(issue, {:issue => {is_resolved: "true", end_date: Date.today}}), method: :put, class: "small-link" %>
      </div>
      <div class="comments display-change d-none">
        <% unless issue.comments.blank? %>
          <strong><%= "Comments:" %></strong>
          <% issue.comments.each do |comment| %>
            <p>
              <em><u><%= "Apartment #{comment.user.apartment_number}" %></u></em>
              <%= " - #{comment.content}" %>
            </p>
            <% if current_user == comment.user %>
              <%= link_to "Edit this comment", "#editCommentForIssue_#{issue.id}", class: "small-link", data: {toggle: "modal", target: "#editCommentForIssue_#{issue.id}"} %>
              <%= render 'comments/edit_comment_modal', issue: issue, comment: comment %>
            <% end %>
            <br>
            <br>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="my-3">
  <h2>Past Issues</h2>
  <% @past_issues.each do |issue| %>
    <div class="container-fluid py-2 border-top border-bottom">
      <div class="row">
        <div class="col-xs-12 col-sm-6 clickable">
          <strong>
            <i class="fas fa-angle-right display-change"></i>
            <i class="fas fa-caret-down d-none display-change"></i>
            <%= issue.title.titleize %>
          </strong>
        </div>
        <div class="col-sm-3">
          <%= "posted by: Apartment #{issue.user.apartment_number}" %>
        </div>
        <div class="col-sm">
          <%= "occured on: #{issue.start_date}" %>
        </div>
        <div class="col-sm">
          <%= "resolved on: #{issue.end_date}" %>
        </div>
      </div>
      <div class="d-none display-change pt-1">
        <p>
          <%= issue.body %>
        </p>
        <%= link_to "Add a comment", "#", class: "small-link" %>
        -
        <%= link_to "Mark issue as ongoing", issue_path(issue, {:issue => {is_resolved: "false"}}), method: :put, class: "small-link" %>
      </div>
    </div>
  <% end %>
</div>

app/views/issues/_new_issue_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
  Add your issue
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">New Issue</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'issues/form', issue: Issue.new %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <title>Broughton</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <div class="banner mb-3"></div>
    <div class="container">
      <%= render 'shared/navbar' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/messages/_new.html.erb
<%= simple_form_for @message, url: create_message_url do |f| %>
  <%= @message.errors.full_messages.join(', ') %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Your name', placeholder: 'Joe Bags' %>
    <%= f.input :email, label: 'Your email address', placeholder: 'joe@example.com' %>
    <%= f.input :body, as: :text, label: 'Your message', placeholder: "Let's have some cake!" %>
  </div>
  <%= recaptcha_tags %>
  <br>
  <%= f.button :submit, 'Send', class: "btn-block btn-outline-primary" %>
<% end %>

app/views/messages/new.html.erb
<div class="wrapper-contact">
  <h1>Contact the residents</h1>
  <br>
  <%= render 'new' %>
</div>

app/views/pages/_contact_information.html.erb
<div class="my-4">
  <h2>Coastline Property Management</h2>
  <u>Jonathan Haley</u>
  <br>
  <strong>Office Phone Number:</strong> (912) 417-4629
  <br>
  <strong>Property Manager's Cell Phone:</strong> (912) 247-0447
  <br>
  <strong>email:</strong> jonathan@coastlinegeorgia.com
  <br>
</div>
<div class="my-4">
  <h2>White Rabbit Lounge's Property Manager:</h2>
  <u>Quito Anderson</u>
  <br>
  <strong>email:</strong> quito@bencarterenterprises.com
  <br>
</div>

app/views/pages/home.html.erb
<div class="wrapper-home">
  <h1>111 W Broughton Street Tenant Association</h1>
  <br>
  <p>
    This website serves as a communication tool for the residents of 111 W Broughton Street in Savannah. It is <em>not</em> affiliated with the Coastline Property Management company.
  </p>
  <p>
    As a tenant, you can document issues and post comments regarding your experience living in the 111 W Broughton Street Apartments. You can also use this site to view correspondance between the residents of 111 W Broughton and other parties.
  </p>
  <p>
    As a visitor, you may download a copy of the anonymized tenant issue report, or contact the tenant association directly.
  </p>
  <br>
</div>
<div class="container-fluid">
  <div class="row justify-content-around">
    <div class="col-xs-12 col-sm-3">
      <% if user_signed_in? %>
      <%= link_to residents_path do %>
          <button class="btn btn-outline-primary">Tenant Portal</button>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <button class="btn btn-outline-primary">Tenant Login</button>
        <% end %>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-3">
      <button class="btn btn-outline-primary" data-toggle="modal" data-target="#report">Download Issues Report</button>
      <%= render 'shared/modal', modal_id: "report", modal_title: "Issues Report", modal_body: "The report will be available in one week", submit: false %>
    </div>
    <div class="col-xs-12 col-sm-3">
      <%= link_to new_message_path do %>
        <button class="btn btn-outline-primary">Contact Tenants</button>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/residents.html.erb
<h1>Resident Portal</h1>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="comments-tab" data-toggle="tab" href="#comments" role="tab" aria-controls="comments" aria-selected="true">Issues & Comments</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="documents-tab" data-toggle="tab" href="#documents" role="tab" aria-controls="documents" aria-selected="false">Documents & Correspondance</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Contact Information</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="comments" role="tabpanel" aria-labelledby="comments-tab">
    <%= render 'issues/issue_list' %>
  </div>
  <div class="tab-pane fade" id="documents" role="tabpanel" aria-labelledby="documents-tab">(coming soon)</div>
  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
    <%= render 'contact_information' %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer"></div>

app/views/shared/_modal.html.erb
<div class="modal fade" id=<%= modal_id %> tabindex="-1" role="dialog" aria-labelledby=<%= "#{modal_id}Title" %> aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id=<%= "#{modal_id}Title" %>>
          <%= modal_title %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= modal_body %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <% unless submit == false %>
          <button type="button" class="btn btn-primary">Submit</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-broughton">
  <% unless current_page?(root_path) %>
    <%= link_to root_path do %>
      <button type="button" class="btn btn-outline-info">Home</button>
    <% end %>
  <% end %>
  <% if user_signed_in? %>
    <%= link_to destroy_user_session_path, method: :delete do %>
      <button type="button" class="btn btn-outline-danger">Logout</button>
    <% end %>
  <% end %>
</div>